server:
  port: ${PORT}
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://${PG_DOMAIN_NAME}:${PG_PORT}/${PG_DB_NAME}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

cache:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    user: ${REDIS_USER}
    password: ${REDIS_PASSWORD}
