server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

cache:
  redis:
    host: ${CACHE_REDIS_HOST}
    port: ${CACHE_REDIS_PORT}
    user: ${CACHE_REDIS_USER}
    password: ${CACHE_REDIS_PASSWORD}
